### ISSUE TITLE
Change woman-programmer icon

### ISSUE THREAD

**Issue by galchenok** [gomzyakov/gomzyakov.github.io#10]

**Comment by galchenok** [comment]
![image](https://user-images.githubusercontent.com/19820340/63248602-1d521880-c281-11e9-91fb-1aea63cc9756.png)

**Comment by gomzyakov** [comment]
![image](https://user-images.githubusercontent.com/1460709/63250855-03670480-c286-11e9-8c8d-87707fd5b31e.png)
