### ISSUE TITLE
Add page for 404 error code

### ISSUE THREAD

**Issue by gomzyakov** [gomzyakov/gomzyakov.github.io#50]
Like in https://github.com/good-first-issues/good-first-issues.github.io/pull/50

**Comment by akshitjain2004** [comment]
Can you assign this issue to me > @gomzyakov. Do you have any specific requirement?

**Comment by gomzyakov** [comment]
@akshitjain2004 Hello!

I assigned a task to you. No specific requirements, everything is as in the example)

**Comment by akshitjain2004** [comment]
@gomzyakov  Hey actually I couldn't find the example. Can you please share a screenshot? So I can work on that

**Comment by gomzyakov** [comment]
> @gomzyakov  Hey actually I couldn't find the example. Can you please share a screenshot? So I can work on that

Example here https://github.com/good-first-issues/good-first-issues.github.io/pull/50

**Comment by divyakelaskar** [comment]
Can i work on this one? (_as currently there is no assignees_)

**Comment by gomzyakov** [comment]
> Can i work on this one? (_as currently there is no assignees_)

@divyakelaskar Yes, sure)
